package view;

import controller.MetronomeController;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.MetronomeModel;

/**
 * classe de l'interface du métronome
 *
 * @author fc891239
 */
public class MetronomeView extends javax.swing.JFrame implements iObserver {

    private MetronomeController controleur;
    private MetronomeModel modele;
    private Son beep;
    private Localization localization;
    boolean friends[];

    public MetronomeView(final MetronomeController controleur, MetronomeModel modele) {
        if (controleur == null || modele == null) {
            throw new NullPointerException("Le contrôleur ou le modèle ne peut être null dans la vue");
        }

        initComponents();

        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                controleur.enregistrer();
            }
        });

        /*
         * Set the Nimbus look and feel
         */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MetronomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MetronomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MetronomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MetronomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        this.controleur = controleur;
        this.modele = modele;
        pnlLEDTempo.setVisible(false);
        pnlLEDMesure.setVisible(false);
        beep = new Son();
        localization = Localization.getLocalization();

    }

    public void startThread() {
        final MetronomeView me = this;
        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                me.setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        btnDemarrer = new javax.swing.JButton();
        btnMoinsMesure = new javax.swing.JButton();
        lblMesure = new javax.swing.JLabel();
        lblChiffreTempo = new javax.swing.JLabel();
        lblChiffreMesure = new javax.swing.JLabel();
        lblTempoCentre = new javax.swing.JLabel();
        lblMesureCentre = new javax.swing.JLabel();
        btnPlusMesure = new javax.swing.JButton();
        btnArreter = new javax.swing.JButton();
        lblTempo = new javax.swing.JLabel();
        lblVolume = new javax.swing.JLabel();
        sldVolume = new javax.swing.JSlider();
        btnAnglais = new javax.swing.JButton();
        btnFrancais = new javax.swing.JButton();
        sldTempo = new javax.swing.JSlider();
        lblLangage = new javax.swing.JLabel();
        pnlLEDTempo = new javax.swing.JPanel();
        pnlLEDMesure = new javax.swing.JPanel();
        lbl40 = new javax.swing.JLabel();
        lbl208 = new javax.swing.JLabel();
        canvas1 = new java.awt.Canvas();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Métronome");
        setMinimumSize(new java.awt.Dimension(464, 265));
        setName("frmVue"); // NOI18N
        setPreferredSize(new java.awt.Dimension(464, 265));
        setResizable(false);

        pnlPrincipal.setBackground(new java.awt.Color(51, 153, 255));
        pnlPrincipal.setMinimumSize(new java.awt.Dimension(464, 230));
        pnlPrincipal.setPreferredSize(new java.awt.Dimension(464, 260));

        btnDemarrer.setText("Démarrer");
        btnDemarrer.setName("btnDemarrer"); // NOI18N
        btnDemarrer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDemarrerMouseClicked(evt);
            }
        });

        btnMoinsMesure.setText("Moins");
        btnMoinsMesure.setName("btnMoinsMesure"); // NOI18N
        btnMoinsMesure.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMoinsMesureMouseClicked(evt);
            }
        });

        lblMesure.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblMesure.setText("Mesure");
        lblMesure.setName("lblMesure"); // NOI18N

        lblChiffreTempo.setBackground(new java.awt.Color(102, 255, 255));
        lblChiffreTempo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblChiffreTempo.setText("120");
        lblChiffreTempo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblChiffreMesure.setBackground(new java.awt.Color(204, 204, 255));
        lblChiffreMesure.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblChiffreMesure.setText("4");
        lblChiffreMesure.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTempoCentre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTempoCentre.setText("Tempo");

        lblMesureCentre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblMesureCentre.setText("Mesure");

        btnPlusMesure.setText("Plus");
        btnPlusMesure.setName("btnPlusMesure"); // NOI18N
        btnPlusMesure.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlusMesureMouseClicked(evt);
            }
        });

        btnArreter.setText("Arrêter");
        btnArreter.setName("btnArreter"); // NOI18N
        btnArreter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnArreterMouseClicked(evt);
            }
        });

        lblTempo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTempo.setText("Tempo");
        lblTempo.setName("lblTempo"); // NOI18N

        lblVolume.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblVolume.setText("Volume");
        lblVolume.setName("lblVolume"); // NOI18N

        sldVolume.setBackground(new java.awt.Color(51, 153, 255));
        sldVolume.setMajorTickSpacing(1);
        sldVolume.setMinorTickSpacing(1);
        sldVolume.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sldVolumeMouseReleased(evt);
            }
        });

        btnAnglais.setText("English");
        btnAnglais.setMaximumSize(new java.awt.Dimension(73, 23));
        btnAnglais.setMinimumSize(new java.awt.Dimension(73, 23));
        btnAnglais.setName("btnAnglais"); // NOI18N
        btnAnglais.setPreferredSize(new java.awt.Dimension(73, 23));
        btnAnglais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnglaisActionPerformed(evt);
            }
        });

        btnFrancais.setText("Français");
        btnFrancais.setName("btnFrancais"); // NOI18N
        btnFrancais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrancaisActionPerformed(evt);
            }
        });

        sldTempo.setBackground(new java.awt.Color(51, 153, 255));
        sldTempo.setMaximum(208);
        sldTempo.setMinimum(40);
        sldTempo.setMinorTickSpacing(1);
        sldTempo.setValue(120);
        sldTempo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sldTempoMouseReleased(evt);
            }
        });
        sldTempo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldTempoStateChanged(evt);
            }
        });

        lblLangage.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblLangage.setText("Langage");
        lblLangage.setName("lblLangage"); // NOI18N

        pnlLEDTempo.setBackground(new java.awt.Color(153, 255, 51));
        pnlLEDTempo.setName(""); // NOI18N

        javax.swing.GroupLayout pnlLEDTempoLayout = new javax.swing.GroupLayout(pnlLEDTempo);
        pnlLEDTempo.setLayout(pnlLEDTempoLayout);
        pnlLEDTempoLayout.setHorizontalGroup(
            pnlLEDTempoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        pnlLEDTempoLayout.setVerticalGroup(
            pnlLEDTempoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        pnlLEDMesure.setBackground(new java.awt.Color(255, 51, 51));
        pnlLEDMesure.setName("LED2"); // NOI18N

        javax.swing.GroupLayout pnlLEDMesureLayout = new javax.swing.GroupLayout(pnlLEDMesure);
        pnlLEDMesure.setLayout(pnlLEDMesureLayout);
        pnlLEDMesureLayout.setHorizontalGroup(
            pnlLEDMesureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        pnlLEDMesureLayout.setVerticalGroup(
            pnlLEDMesureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        lbl40.setText("40");

        lbl208.setText("208");

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAnglais, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLangage)
                            .addComponent(btnFrancais, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVolume)))
                    .addComponent(sldVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMoinsMesure, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblTempo)
                                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblTempoCentre)
                                            .addComponent(lblChiffreTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(pnlLEDTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pnlLEDMesure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMesureCentre)
                                    .addComponent(lblChiffreMesure, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(83, 83, 83)
                                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMesure)
                                    .addComponent(btnArreter, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDemarrer, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPlusMesure, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(14, 14, 14)
                        .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbl40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sldTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl208)))
                .addContainerGap(0, Short.MAX_VALUE))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pnlLEDTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pnlLEDMesure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTempoCentre)
                                    .addComponent(lblMesureCentre))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblChiffreMesure)
                                    .addComponent(lblChiffreTempo)
                                    .addComponent(lblMesure)))
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addComponent(btnDemarrer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnArreter)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPlusMesure)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMoinsMesure)
                        .addGap(9, 9, 9))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addComponent(lblLangage)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnFrancais)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAnglais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(97, 97, 97)))
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTempo)
                    .addComponent(lblVolume))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sldVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl40)
                    .addComponent(lbl208)
                    .addComponent(sldTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(526, 526, 526)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(391, 391, 391)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sldTempoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldTempoStateChanged
        lblChiffreTempo.setText(Integer.toString(sldTempo.getValue()));
    }//GEN-LAST:event_sldTempoStateChanged

    private void btnDemarrerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDemarrerMouseClicked
        controleur.onStart();
    }//GEN-LAST:event_btnDemarrerMouseClicked

    private void btnArreterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnArreterMouseClicked
        controleur.onStop();
    }//GEN-LAST:event_btnArreterMouseClicked

    private void btnPlusMesureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlusMesureMouseClicked
        controleur.onMesureChange(getMesure() + 1);
    }//GEN-LAST:event_btnPlusMesureMouseClicked

    private void btnMoinsMesureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMoinsMesureMouseClicked
        controleur.onMesureChange(getMesure() - 1);
    }//GEN-LAST:event_btnMoinsMesureMouseClicked

    private void sldTempoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sldTempoMouseReleased
        controleur.onTempoChange(getTempo());
    }//GEN-LAST:event_sldTempoMouseReleased

    private void sldVolumeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sldVolumeMouseReleased
        controleur.onVolumeChange(getVolume());
    }//GEN-LAST:event_sldVolumeMouseReleased

    private void btnFrancaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrancaisActionPerformed
        controleur.onFrancais();
    }//GEN-LAST:event_btnFrancaisActionPerformed

    private void btnAnglaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnglaisActionPerformed
        controleur.onAnglais();
    }//GEN-LAST:event_btnAnglaisActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnglais;
    private javax.swing.JButton btnArreter;
    private javax.swing.JButton btnDemarrer;
    private javax.swing.JButton btnFrancais;
    private javax.swing.JButton btnMoinsMesure;
    private javax.swing.JButton btnPlusMesure;
    private java.awt.Canvas canvas1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl208;
    private javax.swing.JLabel lbl40;
    private javax.swing.JLabel lblChiffreMesure;
    private javax.swing.JLabel lblChiffreTempo;
    private javax.swing.JLabel lblLangage;
    private javax.swing.JLabel lblMesure;
    private javax.swing.JLabel lblMesureCentre;
    private javax.swing.JLabel lblTempo;
    private javax.swing.JLabel lblTempoCentre;
    private javax.swing.JLabel lblVolume;
    private javax.swing.JPanel pnlLEDMesure;
    private javax.swing.JPanel pnlLEDTempo;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JSlider sldTempo;
    private javax.swing.JSlider sldVolume;
    // End of variables declaration//GEN-END:variables

    /*
     * définition de la mise à jour de la vue quand le modèle est changé
     */
    @Override
    public void mettreAJour() {
        if (modele.isTick()) {
            beep.jouer(modele.getVolume());
            clignoterLEDTemps();
            if (modele.isPremierTemps()) {
                clignoterLEDMesure();
            }
            try {
                Thread.sleep(200);
            } catch (InterruptedException ex) {
                Logger.getLogger(MetronomeView.class.getName()).log(Level.SEVERE, null, ex);
            }
            pnlLEDTempo.setVisible(false);

            pnlLEDMesure.setVisible(false);
        } else {
            setMesure(modele.getMesure());
            setTempo(modele.getTempo());
            setVolume(modele.getVolume());
            setLangage(modele.getLangage());
        }
    }

    public int getTempo() {
        return Integer.parseInt(lblChiffreTempo.getText());
    }

    public int getMesure() {
        return Integer.parseInt(lblChiffreMesure.getText());
    }

    public int getVolume() {
        return sldVolume.getValue();
    }

    public void setTempo(int tempo) {
        lblChiffreTempo.setText(tempo + "");
        sldTempo.setValue(tempo);
    }

    public void setMesure(int mesure) {
        lblChiffreMesure.setText(mesure + "");
    }

    public void setVolume(int volume) {
        sldVolume.setValue(volume);
    }

    public void setLangage(String langage) {
        if (langage.equals("Francais")) {
            localization.setLangueFrancaise();
        } else if (langage.equals("Anglais")) {
            localization.setLangueAnglaise();
        }
        mettreLaLangueAJour();
    }

    /*
     * méthode qui fait apparaitre la lumière du temps
     */
    private void clignoterLEDTemps() {
        System.out.println("Laide" + modele.getCurrentMesure());
        pnlLEDTempo.setVisible(true);

    }

    /*
     * méthode qui fait apparaitre la lumière de la mesure
     */
    private void clignoterLEDMesure() {
        pnlLEDMesure.setVisible(true);
    }

    private void mettreLaLangueAJour() {
        lblLangage.setText(localization.getWord("Langage"));
        lblMesure.setText(localization.getWord("Mesure"));
        lblMesureCentre.setText(localization.getWord("Mesure"));
        lblTempo.setText(localization.getWord("Tempo"));
        lblTempoCentre.setText(localization.getWord("Tempo"));
        lblVolume.setText(localization.getWord("Volume"));
        //btnAnglais.setText(localization.getWord("Anglais"));
        //btnFrancais.setText(localization.getWord("Français"));
        btnPlusMesure.setText(localization.getWord("Plus"));
        btnMoinsMesure.setText(localization.getWord("Moins"));
        btnDemarrer.setText(localization.getWord("Démarrer"));
        btnArreter.setText(localization.getWord("Arrêter"));
    }
}
